.TH BEAV 1 "" "" \" -*- nroff -*-
.SH NAME
beav \- binary file editor and viewer
.SH SYNOPSIS
.B beav
[file...]
.SH DESCRIPTION
This is a brief description of the minimal set of commands
that are necessary to start using
.IR beav
effectively.
For more information, review the file /usr/share/doc/beav/beav140.txt.gz.
.PP
The \fIfile-visit\fR command,\fB Ctl-X Ctl-V\fR, can be used to read a
file in for editing.   The file can also be read in from the
command line; \fBbeav <edit_file>\fR.
.PP
Data is displayed in one or more windows.
These commands can be used to navigate around the windows.
.PP
.RS
\fImove-back-char\fB      Ctl-B\fB     moves left\fR
.br
\fImove-back-line\fB      Ctl-P\fB     moves up\fR
.br
\fImove-forw-char\fb      Ctl-F\fB     moves right\fR
.br
\fImove-forw-line\fB      Ctl-N\fB     moves down\fR
.br
\fIwindow-delete\fB       Ctl-X 0\fB   delete window\fR
.br
\fIwindow-expand\fB       Ctl-X 1\fB   expand window\fR
.br
.RE
.PP
The \fImove-to-byte\fR command,\fB Ctl-X G\fR, will prompt you for a
byte position to move to.
.PP
These commands will insert a zero byte at the cursor
position or delete the byte at that position.
.PP
.RS
\fIinsert-unit\fB         Ctl-X I\fR
.br
\fIdelete-forw-unit\fB    Esc D\fR
.br
.RE
.PP
The \fIfile-save\fR command,\fB Ctl-X Ctl-S\fR, will save the data to
the file if a change has been made.
.PP
The \fIhelp\fR command,\fB Esc ?\fR, will display a list of all
commands and their current key bindings.
.PP
The \fIabort-cmd\fR command,\fB Ctl-G\fR, will abort any command that
is in operation.
.PP
The \fIquit-no-save\fR command,\fB Ctl-X Ctl-C\fR, will exit beav.
If there is any data that has not been saved you will be warned.
.PP
.SH FILES
/usr/share/doc/beav/beav140.txt.gz

