# This is a makefile for 286 xenix
CFLAGS=     -O -Ml -DUNIX -DNOPROTO -DNORENAME

OFILES=		basic.o ebcdic.o fileio.o region.o text.o wangpc.o \
	language.obj buffer.o echo.o main.o search.o tty.o window.o \
	cinfo.o extend.o kbd.o spawn.o ttyio.o termio.o tcap.o word.o \
	display.o file.o line.o random.o symbol.o ttykbd.o format.o


CFILES=     basic.c ebcdic.c fileio.c region.c text.c wangpc.c \
	buffer.c echo.c language.c format.c main.c search.c tty.c window.c \
	cinfo.c extend.c kbd.c spawn.c ttyio.c termio.c tcap.c word.c \
	display.c file.c line.c random.c symbol.c ttykbd.c

HFILES=     def.h

beav:     $(OFILES)
	$(CC) $(CFLAGS) $(OFILES) -ltermcap -lc -o beav

(OFILES):  $(HFILES)

